# Generated by Django 5.1.5 on 2025-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_alter_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timeread',
            field=models.CharField(default=15, max_length=200),
            preserve_default=False,
        ),
    ]
