# Generated by Django 5.1.5 on 2025-02-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blockquote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
