# Generated by Django 5.1.5 on 2025-02-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_blog_blockquote_blog_content2_blog_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
