# Generated by Django 5.1.5 on 2025-02-09 20:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_blog_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content2',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
