# Generated by Django 5.1.5 on 2025-02-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0011_alter_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title3',
        ),
    ]
