# Generated by Django 5.1.5 on 2025-02-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0012_remove_blog_content3_remove_blog_title3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
