# Generated by Django 5.1.5 on 2025-02-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
